version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:12.12"
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ${POSTGRES_PGDATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - db-network
  backend:
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    build: ./backend/.
    image: "kupi-backend"
    ports:
      - "3032:3001"
    restart: unless-stopped
    networks:
      - db-network
      - frontend-network
networks:
  db-network:
    driver: bridge
    internal: true
  frontend-network:
    driver: bridge